"""Add national pet registrations table

Revision ID: 7e7cb1ec6750
Revises: 489ca985fff4
Create Date: 2025-07-29 21:40:24.869498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7cb1ec6750'
down_revision = '489ca985fff4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 